name: educonnect
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analysis_options: ^2.0.1
  cached_network_image: ^3.3.0
  chewie: 1.7.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dash_chat_2: ^0.0.20
  dio: ^4.0.0
  encrypt_shared_preferences: ^0.7.1
  equatable: ^2.0.3
  fast_cached_network_image: ^1.0.1
  file_picker: 8.0.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_polls: ^0.1.6
  flutter_secure_storage: ^9.1.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_vlc_player: ^7.4.1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.5.0
  get_it: ^7.2.0
  http: ^1.0.0
  http_parser: ^4.0.2
  image_picker: ^1.0.8
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^0.0.1+4
  laravel_echo_null: ^0.0.6
  logger: ^2.3.0
  pin_code_fields: ^8.0.1
  pusher_channels_flutter: ^2.2.1
  search_page: ^2.3.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.0.10
  video_player: 2.8.5
dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/manageSchool/
    - assets/images/post/
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
